logging:
   level:
     com.atomist.spring.agent: DEBUG

atomist:
  enabled: true
  debug: true
  url: 'https://webhook.atomist.com/atomist/application/teams/T1JVCMVH7'
  environment:
      domain: '${ATOMIST_ENVIRONMENT:development}'
      pod: '${HOSTNAME:${random.value}}'
